module.exports = {
  '42': '42 Coin',
  '365': '365Coin',
  '404': '404Coin',
  '611': 'SixEleven',
  '808': '808',
  '888': 'Octocoin',
  '1337': '1337',
  '2015': '2015 coin',
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  LTC: 'Litecoin',
  DASH: 'DigitalCash',
  XMR: 'Monero',
  NXT: 'Nxt',
  ETC: 'Ethereum Classic',
  DOGE: 'Dogecoin',
  ZEC: 'ZCash',
  BTS: 'Bitshares',
  DGB: 'DigiByte',
  XRP: 'Ripple',
  BTCD: 'BitcoinDark',
  PPC: 'PeerCoin',
  CRAIG: 'CraigsCoin',
  XBS: 'Bitstake',
  XPY: 'PayCoin',
  PRC: 'ProsperCoin',
  YBC: 'YbCoin',
  DANK: 'DarkKush',
  GIVE: 'GiveCoin',
  KOBO: 'KoboCoin',
  DT: 'DarkToken',
  CETI: 'CETUS Coin',
  SUP: 'Supcoin',
  XPD: 'PetroDollar',
  GEO: 'GeoCoin',
  CHASH: 'CleverHash',
  SPR: 'Spreadcoin',
  NXTI: 'NXTI',
  WOLF: 'Insanity Coin',
  XDP: 'DogeParty',
  AC: 'Asia Coin',
  ACOIN: 'ACoin',
  AERO: 'Aero Coin',
  ALF: 'AlphaCoin',
  AGS: 'Aegis',
  AMC: 'AmericanCoin',
  ALN: 'AlienCoin',
  APEX: 'ApexCoin',
  ARCH: 'ArchCoin',
  ARG: 'Argentum',
  ARI: 'AriCoin',
  AUR: 'Aurora Coin',
  AXR: 'AXRON',
  BCX: 'BattleCoin',
  BEN: 'Benjamins',
  BET: 'BetaCoin',
  BITB: 'BitBean',
  BLU: 'BlueCoin',
  BLK: 'BlackCoin',
  BOST: 'BoostCoin',
  BQC: 'BQCoin',
  XMY: 'MyriadCoin',
  MOON: 'MoonCoin',
  ZET: 'ZetaCoin',
  SXC: 'SexCoin',
  QTL: 'Quatloo',
  ENRG: 'EnergyCoin',
  QRK: 'QuarkCoin',
  RIC: 'Riecoin',
  DGC: 'DigiCoin',
  LIMX: 'LimeCoinX',
  BTB: 'BitBar',
  CAIX: 'CAIx',
  'BTG*': 'BitGem',
  BTM: 'BitMark',
  BUK: 'CryptoBuk',
  CACH: 'Cachecoin',
  CANN: 'CannabisCoin',
  CAP: 'BottleCaps',
  CAT: 'Catcoin',
  CBX: 'CryptoBullion',
  CCN: 'CannaCoin',
  CIN: 'CinderCoin',
  CINNI: 'CINNICOIN',
  CXC: 'CheckCoin',
  CLAM: 'CLAMS',
  CLOAK: 'CloakCoin',
  CLR: 'CopperLark',
  CMC: 'CosmosCoin',
  CNC: 'ChinaCoin',
  CNL: 'ConcealCoin',
  COMM: 'Community Coin',
  COOL: 'CoolCoin',
  CRACK: 'CrackCoin',
  CRC: 'CraftCoin',
  CRYPT: 'CryptCoin',
  CSC: 'CasinoCoin',
  DEM: 'eMark',
  DMD: 'Diamond',
  XVG: 'Verge',
  DRKC: 'DarkCash',
  DSB: 'DarkShibe',
  DVC: 'DevCoin',
  EAC: 'EarthCoin',
  EFL: 'E-Gulden',
  ELC: 'Elacoin',
  EMC2: 'Einsteinium',
  EMD: 'Emerald',
  EXCL: 'Exclusive Coin',
  EXE: 'ExeCoin',
  EZC: 'EZCoin',
  FLAP: 'Flappy Coin',
  FC2: 'Fuel2Coin',
  FFC: 'FireflyCoin',
  FIBRE: 'FIBRE',
  FRC: 'FireRoosterCoin',
  FLT: 'FlutterCoin',
  FRK: 'Franko',
  FRAC: 'FractalCoin',
  FST: 'FastCoin',
  FTC: 'FeatherCoin',
  GDC: 'GrandCoin',
  GLC: 'GlobalCoin',
  GLD: 'GoldCoin',
  GLX: 'GalaxyCoin',
  GLYPH: 'GlyphCoin',
  GML: 'GameLeagueCoin',
  GUE: 'GuerillaCoin',
  HAL: 'Halcyon',
  HBN: 'HoboNickels',
  HUC: 'HunterCoin',
  HVC: 'HeavyCoin',
  HYP: 'Hyperstake',
  ICB: 'IceBergCoin',
  IFC: 'Infinite Coin',
  IOC: 'IOCoin',
  IXC: 'IXcoin',
  JBS: 'JumBucks Coin',
  JKC: 'JunkCoin',
  JUDGE: 'JudgeCoin',
  KDC: 'Klondike Coin',
  KEY: 'KeyCoin',
  KGC: 'KrugerCoin',
  'LAB*': 'CoinWorksCoin',
  'LGD*': 'Legendary Coin',
  LK7: 'Lucky7Coin',
  LKY: 'LuckyCoin',
  LSD: 'LightSpeedCoin',
  LTB: 'Litebar ',
  LTCD: 'LitecoinDark',
  LTCX: 'LitecoinX',
  LXC: 'LibrexCoin',
  LYC: 'LycanCoin',
  MAX: 'MaxCoin',
  MEC: 'MegaCoin',
  MED: 'MediterraneanCoin',
  MIN: 'Minerals Coin',
  MINT: 'MintCoin',
  MN: 'Cryptsy Mining Contract',
  MNC: 'MinCoin',
  MRY: 'MurrayCoin',
  'MYST*': 'MysteryCoin',
  MZC: 'MazaCoin',
  NAN: 'NanoToken',
  NAUT: 'Nautilus Coin',
  NAV: 'NavCoin',
  NBL: 'Nybble',
  NEC: 'NeoCoin',
  NET: 'NetCoin',
  NMB: 'Nimbus Coin',
  NRB: 'NoirBits',
  NOBL: 'NobleCoin',
  NRS: 'NoirShares',
  NVC: 'NovaCoin',
  NMC: 'NameCoin',
  NYAN: 'NyanCoin',
  OPAL: 'OpalCoin',
  ORB: 'Orbitcoin',
  OSC: 'OpenSourceCoin',
  PHS: 'PhilosophersStone',
  POINTS: 'Cryptsy Points',
  POT: 'PotCoin',
  PSEUD: 'PseudoCash',
  'PTS*': 'Protoshares',
  PXC: 'PhoenixCoin',
  PYC: 'PayCoin',
  RDD: 'ReddCoin',
  RIPO: 'RipOffCoin',
  RT2: 'RotoCoin',
  RYC: 'RoyalCoin',
  RZR: 'RazorCoin',
  SAT2: 'Saturn2Coin',
  SBC: 'StableCoin',
  SDC: 'ShadowCash',
  SFR: 'SaffronCoin',
  SHADE: 'ShadeCoin',
  SHLD: 'ShieldCoin',
  SILK: 'SilkCoin',
  SLG: 'SterlingCoin',
  SMC: 'SmartCoin',
  SOLE: 'SoleCoin',
  SPA: 'SpainCoin',
  SPT: 'Spots',
  SRC: 'SecureCoin',
  SSV: 'SSVCoin',
  XLM: 'Stellar',
  SUPER: 'SuperCoin',
  SWIFT: 'BitSwift',
  SYNC: 'SyncCoin',
  SYS: 'SysCoin',
  TAG: 'TagCoin',
  TAK: 'TakCoin',
  TES: 'TeslaCoin',
  TGC: 'TigerCoin',
  TIT: 'TitCoin',
  TOR: 'TorCoin',
  TRC: 'TerraCoin',
  TTC: 'TittieCoin',
  ULTC: 'Umbrella',
  UNO: 'Unobtanium',
  URO: 'UroCoin',
  USDE: 'UnitaryStatus Dollar',
  UTC: 'UltraCoin',
  UTIL: 'Utility Coin',
  VDO: 'VidioCoin',
  VIA: 'ViaCoin',
  VOOT: 'VootCoin',
  VRC: 'VeriCoin',
  VTC: 'VertCoin',
  WC: 'WhiteCoin',
  WDC: 'WorldCoin',
  XAI: 'SapienceCoin',
  XBOT: 'SocialXbotCoin',
  XC: 'X11 Coin',
  XCASH: 'Xcash',
  XCR: 'Crypti',
  XJO: 'JouleCoin',
  XLB: 'LibertyCoin',
  XPM: 'PrimeCoin',
  XST: 'StealthCoin',
  XXX: 'XXXCoin',
  YAC: 'YAcCoin',
  ZCC: 'ZCC Coin',
  ZED: 'ZedCoins',
  'ZRC*': 'ZiftrCoin',
  BCN: 'ByteCoin',
  EKN: 'Elektron',
  XDN: 'DigitalNote ',
  XAU: 'XauCoin',
  TMC: 'TimesCoin',
  XEM: 'NEM',
  BURST: 'BurstCoin',
  NBT: 'NuBits',
  SJCX: 'StorjCoin',
  START: 'StartCoin',
  HUGE: 'BigCoin',
  XCP: 'CounterParty',
  MAID: 'MaidSafe Coin',
  '007': '007 coin',
  NSR: 'NuShares',
  MONA: 'MonaCoin',
  CELL: 'SolarFarm',
  TEK: 'TekCoin',
  TRON: 'Positron',
  BAY: 'BitBay',
  NTRN: 'Neutron',
  SLING: 'Sling Coin',
  XVC: 'Vcash',
  CRAVE: 'CraveCoin',
  BLOCK: 'BlockNet',
  XSI: 'Stability Shares',
  GHS: 'Giga Hash',
  BYC: 'ByteCent',
  GRC: 'GridCoin',
  GEMZ: 'Gemz Social',
  KTK: 'KryptCoin',
  HZ: 'Horizon',
  FAIR: 'FairCoin',
  QORA: 'QoraCoin',
  NLG: 'Gulden',
  RBY: 'RubyCoin',
  PTC: 'PesetaCoin',
  KORE: 'Kore',
  WBB: 'Wild Beast Coin',
  SSD: 'Sonic Screw Driver Coin',
  XTC: 'TileCoin',
  NOTE: 'Dnotes',
  'GRID*': 'GridPay',
  FLO: 'FlorinCoin',
  MMXIV: 'MaieutiCoin',
  '8BIT': '8BIT Coin',
  STV: 'Sativa Coin',
  EBS: 'EbolaShare',
  AM: 'AeroMe',
  XMG: 'Coin Magi',
  AMBER: 'AmberCoin',
  JPC: 'JackPotCoin',
  NKT: 'NakomotoDark',
  J: 'JoinCoin',
  GHC: 'GhostCoin',
  'DTC*': 'DayTrader Coin',
  ABY: 'ArtByte',
  LDOGE: 'LiteDoge',
  MTR: 'MasterTraderCoin',
  TRI: 'Triangles Coin',
  SWARM: 'SwarmCoin',
  BBR: 'Boolberry',
  BTCRY: 'BitCrystal',
  BCR: 'BitCredit',
  XPB: 'Pebble Coin',
  XDQ: 'Dirac Coin',
  FLDC: 'Folding Coin',
  SLR: 'SolarCoin',
  SMAC: 'Social Media Coin',
  TRK: 'TruckCoin',
  U: 'Ucoin',
  UIS: 'Unitus',
  CYP: 'CypherPunkCoin',
  UFO: 'UFO Coin',
  ASN: 'Ascension Coin',
  OC: 'OrangeCoin',
  GSM: 'GSM Coin',
  FSC2: 'FriendshipCoin',
  NXTTY: 'NXTTY',
  QBK: 'QuBuck Coin',
  BLC: 'BlakeCoin',
  MARYJ: 'MaryJane Coin',
  OMC: 'OmniCron',
  GIG: 'GigCoin',
  CC: 'CyberCoin',
  BITS: 'BitstarCoin',
  LTBC: 'LTBCoin',
  NEOS: 'NeosCoin',
  HYPER: 'HyperCoin',
  VTR: 'Vtorrent',
  METAL: 'MetalCoin',
  PINK: 'PinkCoin',
  GRE: 'GreenCoin',
  XG: 'XG Sports',
  CHILD: 'ChildCoin',
  BOOM: 'BOOM Coin',
  MINE: 'Instamine Nuggets',
  ROS: 'ROS Coin',
  UNAT: 'Unattanium',
  SLM: 'SlimCoin',
  GAIA: 'GAIA Platform',
  TRUST: 'TrustPlus',
  FCN: 'FantomCoin ',
  XCN: 'Cryptonite',
  CURE: 'Curecoin',
  GMC: 'Gridmaster',
  MMC: 'MemoryCoin',
  XBC: 'BitcoinPlus',
  CYC: 'ConSpiracy Coin ',
  OCTO: 'OctoCoin',
  MSC: 'MasterCoin',
  EGG: 'EggCoin',
  C2: 'Coin.2',
  GSX: 'GlowShares',
  CAM: 'Camcoin',
  RBR: 'Ribbit Rewards',
  XQN: 'Quotient',
  ICASH: 'ICASH',
  NODE: 'Node',
  SOON: 'SoonCoin',
  BTMI: 'BitMiles',
  EVENT: 'Event Token',
  '1CR': '1Credit',
  VIOR: 'ViorCoin',
  XCO: 'XCoin',
  VMC: 'VirtualMining Coin',
  MRS: 'MarsCoin',
  VIRAL: 'Viral Coin',
  EQM: 'Equilibrium Coin',
  ISL: 'IslaCoin',
  QSLV: 'Quicksilver coin',
  XWT: 'World Trade Funds',
  XNA: 'DeOxyRibose',
  RDN: 'RadonPay',
  SKB: 'SkullBuzz',
  BSTY: 'GlobalBoost',
  FCS: 'CryptoFocus',
  GAM: 'Gambit coin',
  NXS: 'Nexus',
  CESC: 'Crypto Escudo',
  TWLV: 'Twelve Coin',
  EAGS: 'EagsCoin',
  MWC: 'MultiWallet Coin',
  ADC: 'AudioCoin',
  MARS: 'MarsCoin ',
  XMS: 'Megastake',
  SPHR: 'Sphere Coin',
  SIGU: 'Singular',
  'BTX*': 'BitcoinTX',
  DCC: 'DarkCrave',
  M1: 'SupplyShock',
  DB: 'DarkBit',
  CTO: 'Crypto',
  EDGE: 'EdgeCoin',
  'LUX*': 'BitLux',
  FUTC: 'FutCoin',
  GLOBE: 'Global',
  TAM: 'TamaGucci',
  MRP: 'MorpheusCoin',
  CREVA: 'Creva Coin',
  XFC: 'Forever Coin',
  NANAS: 'BananaBits',
  LOG: 'Wood Coin',
  XCE: 'Cerium',
  ACP: 'Anarchists Prime',
  DRZ: 'Droidz',
  'BUCKS*': 'GorillaBucks',
  BSC: 'BowsCoin',
  DRKT: 'DarkTron',
  CIRC: 'CryptoCircuits',
  NKA: 'IncaKoin',
  VERSA: 'Versa Token',
  EPY: 'Empyrean',
  SQL: 'Squall Coin',
  POLY: 'PolyBit',
  PIGGY: 'Piggy Coin',
  CHA: 'Charity Coin',
  MIL: 'Milllionaire Coin',
  CRW: 'Crown Coin',
  GEN: 'Genstake',
  XPH: 'PharmaCoin',
  GRM: 'GridMaster',
  QTZ: 'Quartz',
  ARB: 'Arbit Coin',
  LTS: 'Litestar Coin',
  SPC: 'SpinCoin',
  GP: 'GoldPieces',
  BITZ: 'Bitz Coin',
  DUB: 'DubCoin',
  GRAV: 'Graviton',
  BOB: 'Bob Coin',
  MCN: 'MonetaVerde',
  QCN: 'Quazar Coin',
  HEDG: 'Hedgecoin',
  SONG: 'Song Coin',
  XSEED: 'BitSeeds',
  CRE: 'Credits',
  AXIOM: 'Axiom Coin',
  SMLY: 'SmileyCoin',
  RBT: 'Rimbit',
  CHIP: 'Chip',
  SPEC: 'SpecCoin',
  GRAM: 'Gram Coin',
  UNC: 'UnCoin',
  SPRTS: 'Sprouts',
  ZNY: 'BitZeny',
  BTQ: 'BitQuark',
  PKB: 'ParkByte',
  'STR*': 'StarCoin',
  SNRG: 'Synergy',
  GHOUL: 'Ghoul Coin',
  HNC: 'Hellenic Coin',
  DIGS: 'Diggits',
  EXP: 'Expanse',
  GCR: 'Global Currency Reserve',
  MAPC: 'MapCoin',
  MI: 'XiaoMiCoin',
  CON: 'Paycon',
  TX: 'Transfer',
  GRS: 'Groestlcoin ',
  SC: 'Siacoin',
  CLV: 'CleverCoin',
  FCT: 'Factoids',
  LYB: 'LyraBar',
  BST: 'BitStone',
  PXI: 'Prime-X1',
  CPC: 'CapriCoin',
  AMS: 'Amsterdam Coin',
  OBITS: 'Obits Coin',
  CLUB: ' ClubCoin',
  RADS: 'Radium',
  EMC: 'Emercoin',
  BLITZ: 'BlitzCoin',
  'HIRE*': 'BitHIRE',
  EGC: 'EverGreenCoin',
  MND: 'MindCoin',
  I0C: 'I0coin',
  BTA: 'Bata',
  KARM: 'Karmacoin',
  DCR: 'Decred',
  NAS2: 'Nas2Coin',
  PAK: 'Pakcoin',
  CRB: 'Creditbit ',
  DOGED: 'DogeCoinDark',
  REP: 'Augur',
  OK: 'OKCash',
  VOX: 'Voxels',
  AMP: 'Synereo',
  HODL: 'HOdlcoin',
  DGD: 'Digix DAO',
  EDRC: 'EDRCoin',
  LSK: 'Lisk',
  WAVES: 'Waves',
  HTC: 'Hitcoin',
  GAME: 'Gamecredits',
  DSH: 'Dashcoin',
  DBIC: 'DubaiCoin',
  XHI: 'HiCoin',
  SPOTS: 'Spots',
  BIOS: 'BiosCrypto',
  'KNC*': 'Khancoin',
  CAB: 'CabbageUnit',
  DIEM: 'CarpeDiemCoin',
  GBT: 'GameBetCoin',
  SAR: 'SARCoin',
  RCX: 'RedCrowCoin',
  PWR: 'PowerCoin',
  TRUMP: 'TrumpCoin',
  PRM: 'PrismChain',
  BCY: 'BitCrystals',
  RBIES: 'Rubies',
  STEEM: 'Steem',
  BLRY: 'BillaryCoin',
  XWC: 'WhiteCoin',
  DOT: 'Dotcoin',
  SCOT: 'Scotcoin',
  DNET: 'Darknet',
  BAC: 'BitalphaCoin',
  'XID*': 'International Diamond Coin',
  GRT: 'Grantcoin',
  TCR: 'Thecreed',
  POST: 'PostCoin',
  INFX: 'Influxcoin',
  ETHS: 'EthereumScrypt',
  PXL: 'Phalanx',
  NUM: 'NumbersCoin',
  SOUL: 'SoulCoin',
  ION: 'Ionomy',
  GROW: 'GrownCoin',
  UNITY: 'SuperNET',
  OLDSF: 'OldSafeCoin',
  SSTC: 'SunShotCoin',
  NETC: 'NetworkCoin',
  GPU: 'GPU Coin',
  TAGR: 'Think And Get Rich Coin',
  HMP: 'HempCoin',
  ADZ: 'Adzcoin',
  GAP: 'Gapcoin',
  MYC: 'MayaCoin',
  IVZ: 'InvisibleCoin',
  VTA: 'VirtaCoin',
  SLS: 'SaluS',
  SOIL: 'SoilCoin',
  CUBE: 'DigiCube',
  YOC: 'YoCoin',
  'COIN*': 'Coin',
  VPRC: 'VapersCoin',
  APC: 'AlpaCoin',
  STEPS: 'Steps',
  DBTC: 'DebitCoin',
  UNIT: 'Universal Currency',
  AEON: 'AeonCoin',
  MOIN: 'MoinCoin',
  SIB: 'SibCoin',
  ERC: 'EuropeCoin',
  AIB: 'AdvancedInternetBlock',
  PRIME: 'PrimeChain',
  BERN: 'BERNcash',
  BIGUP: 'BigUp',
  KR: 'Krypton',
  XRE: 'RevolverCoin',
  MEME: 'Pepe',
  XDB: 'DragonSphere',
  ANTI: 'Anti Bitcoin',
  BRK: 'BreakoutCoin',
  COLX: 'ColossusCoinXT',
  MNM: 'Mineum',
  ADCN: 'Asiadigicoin',
  ZEIT: 'ZeitCoin',
  '2GIVE': '2GiveCoin',
  CGA: 'Cryptographic Anomaly',
  SWING: 'SwingCoin',
  SAFEX: 'SafeExchangeCoin',
  NEBU: 'Nebuchadnezzar',
  AEC: 'AcesCoin',
  FRN: 'Francs',
  ADN: 'Aiden',
  PULSE: 'Pulse',
  N7: 'Number7',
  CYG: 'Cygnus',
  LGBTQ: 'LGBTQoin',
  UTH: 'Uther',
  MPRO: 'MediumProject',
  KAT: 'KATZcoin',
  SPM: 'Supreme',
  MOJO: 'Mojocoin',
  BELA: 'BelaCoin',
  FLX: 'Flash',
  BOLI: 'BolivarCoin',
  CLUD: 'CludCoin',
  DIME: 'DimeCoin',
  FLY: 'FlyCoin',
  HVCO: 'High Voltage Coin',
  GIZ: 'GIZMOcoin',
  GREXIT: 'GrexitCoin',
  CARBON: 'Carboncoin',
  DEUR: 'DigiEuro',
  TUR: 'Turron',
  LEMON: 'LemonCoin',
  STS: 'STRESScoin',
  DISK: 'Dark Lisk',
  NEVA: 'NevaCoin',
  CYT: 'Cryptokenz',
  FUZZ: 'Fuzzballs',
  NKC: 'Nukecoinz',
  SCRT: 'SecretCoin',
  XRA: 'Ratecoin',
  XNX: 'XanaxCoin',
  'STAR*': 'StarCoin',
  STHR: 'Stakerush',
  DBG: 'Digital Bullion Gold',
  BON: 'BonesCoin',
  WMC: 'WMCoin',
  GOTX: 'GothicCoin',
  FLVR: 'FlavorCoin',
  SHREK: 'ShrekCoin',
  'STA*': 'Stakers',
  RISE: 'Rise',
  REV: 'Revenu',
  PBC: 'PabyosiCoin',
  OBS: 'Obscurebay',
  EXIT: 'ExitCoin',
  EDC: 'EducoinV',
  CLINT: 'Clinton',
  CKC: 'Clockcoin',
  VIP: 'VIP Tokens',
  NXE: 'NXEcoin',
  ZOOM: 'ZoomCoin',
  DRACO: 'DT Token',
  YOVI: 'YobitVirtualCoin',
  ORLY: 'OrlyCoin',
  KUBO: 'KubosCoin',
  INCP: 'InceptionCoin',
  SAK: 'SharkCoin',
  EVIL: 'EvilCoin',
  OMA: 'OmegaCoin',
  MUE: 'MonetaryUnit',
  COX: 'CobraCoin',
  BNT: 'Bancor Network Token',
  EKO: 'EkoCoin',
  BSD: 'BitSend',
  DES: 'Destiny',
  BIT16: '16BitCoin',
  PDC: 'Project Decorum',
  CMT: 'CometCoin',
  CHESS: 'ChessCoin',
  SPACE: 'SpaceCoin',
  REE: 'ReeCoin',
  LQD: 'Liquid',
  MARV: 'Marvelous',
  XDE2: 'XDE II',
  VEC2: 'VectorCoin 2.0 ',
  OMNI: 'Omni',
  GSY: 'GenesysCoin',
  'TKN*': 'TrollTokens',
  LIR: 'Let it Ride',
  MMNXT: 'MMNXT ',
  SCRPT: 'ScryptCoin',
  LBC: 'LBRY Credits',
  SPX: 'Specie',
  SBD: 'Steem Backed Dollars',
  CJ: 'CryptoJacks',
  PUT: 'PutinCoin',
  KRAK: 'Kraken',
  DLISK: 'Dlisk',
  IBANK: 'iBankCoin',
  STRAT: 'Stratis',
  VOYA: 'Voyacoin',
  ENTER: 'EnterCoin (ENTER)',
  WGC: 'World Gold Coin',
  BM: 'BitMoon',
  FRWC: 'Frankywillcoin',
  PSY: 'Psilocybin',
  XT: 'ExtremeCoin',
  RUST: 'RustCoin',
  NZC: 'NewZealandCoin',
  SNGLS: 'SingularDTV',
  XAUR: 'Xaurum',
  BFX: 'BitFinex Tokens',
  UNIQ: 'Uniqredit',
  CRX: 'ChronosCoin',
  DCT: 'Decent',
  XPOKE: 'PokeChain',
  MUDRA: 'MudraCoin',
  WARP: 'WarpCoin',
  CNMT: 'Coinomat',
  PIZZA: 'PizzaCoin',
  LC: 'Lutetium Coin',
  HEAT: 'Heat Ledger',
  ICN: 'Iconomi',
  EXB: 'ExaByte (EXB)',
  WINGS: 'Wings DAO',
  CDX: 'Cryptodex',
  RBIT: 'ReturnBit',
  'DCS.': 'deCLOUDs',
  KMD: 'Komodo',
  GB: 'GoldBlocks',
  NEO: 'NEO',
  ANC: 'Anoncoin',
  SYNX: 'Syndicate',
  MC: 'Mass Coin',
  EDR: 'E-Dinar Coin',
  JWL: 'Jewels',
  WAY: 'WayCoin',
  TAB: 'MollyCoin',
  TRIG: 'Trigger',
  BITCNY: 'bitCNY',
  BITUSD: 'bitUSD',
  ATM: 'Autumncoin',
  STO: 'Save The Ocean',
  SNS: 'Sense',
  FSN: 'Fusion',
  CTC: 'CarterCoin',
  TOT: 'TotCoin',
  BTD: 'Bitcloud',
  BOTS: 'ArkDAO',
  MDC: 'MedicCoin',
  FTP: 'FuturePoints',
  ZET2: 'Zeta2Coin',
  'COV*': 'CovenCoin',
  KRB: 'Karbowanec',
  TELL: 'Tellurion',
  ENE: 'EneCoin',
  TDFB: 'TDFB',
  BLOCKPAY: 'BlockPay',
  BXT: 'BitTokens',
  ZYD: 'ZayedCoin',
  MST: 'MustangCoin',
  GOON: 'Goonies',
  VLT: 'Veltor',
  ZNE: 'ZoneCoin',
  DCK: 'DickCoin',
  COVAL: 'Circuits of Value',
  DGDC: 'DarkGold',
  TODAY: 'TodayCoin',
  VRM: 'Verium',
  ROOT: 'RootCoin',
  '1ST': 'FirstBlood',
  GPL: 'Gold Pressed Latinum',
  DOPE: 'DopeCoin',
  B3: 'B3 Coin',
  FX: 'FCoin',
  PIO: 'Pioneershares',
  GAY: 'GayCoin',
  SMSR: 'Samsara Coin',
  UBIQ: 'Ubiqoin',
  ARM: 'Armory Coin',
  RING: 'RingCoin',
  ERB: 'ERBCoin',
  LAZ: 'Lazarus',
  FONZ: 'FonzieCoin',
  BTCR: 'BitCurrency',
  DROP: 'FaucetCoin',
  SANDG: 'Save and Gain',
  PNK: 'SteamPunk',
  MOOND: 'Dark Moon',
  DLC: 'DollarCoin',
  SEN: 'Sentaro',
  SCN: 'Swiscoin',
  WEX: 'Wexcoin',
  LTH: 'Lathaan',
  BRONZ: 'BitBronze',
  SH: 'Shilling',
  BUZZ: 'BuzzCoin',
  MG: 'Mind Gene',
  PSI: 'PSIcoin',
  XPO: 'Opair',
  NLC: 'NoLimitCoin',
  PSB: 'PesoBit',
  XBTS: 'Beats',
  FIT: 'Fitcoin',
  PINKX: 'PantherCoin',
  FIRE: 'FireCoin',
  UNF: 'Unfed Coin',
  SPORT: 'SportsCoin',
  PPY: 'Peerplays',
  NTC: 'NineElevenTruthCoin',
  EGO: 'EGOcoin',
  'BTCL*': 'BitluckCoin',
  'RCN*': 'RCoin',
  X2: 'X2Coin',
  MT: 'Mycelium Token',
  TIA: 'Tianhe',
  GBRC: 'GBR Coin',
  XUP: 'UPcoin',
  HALLO: 'Halloween Coin',
  BBCC: 'BaseballCardCoin',
  EMIGR: 'EmiratesGoldCoin',
  BHC: 'BighanCoin',
  CRAFT: 'Craftcoin',
  INV: 'Invictus',
  OLYMP: 'OlympCoin',
  DPAY: 'DelightPay',
  ATOM: 'Atomic Coin',
  HKG: 'Hacker Gold',
  ANTC: 'AntiLitecoin',
  JOBS: 'JobsCoin',
  DGORE: 'DogeGoreCoin',
  THC: 'The Hempcoin',
  TRA: 'Tetra',
  RMS: 'Resumeo Shares',
  FJC: 'FujiCoin',
  VAPOR: 'Vaporcoin',
  SDP: 'SydPakCoin',
  RRT: 'Recovery Right Tokens',
  XZC: 'ZCoin',
  PRE: 'Premium',
  CALC: 'CaliphCoin',
  LEA: 'LeaCoin',
  CF: 'Californium',
  CRNK: 'CrankCoin',
  CFC: 'CoffeeCoin',
  VTY: 'Victoriouscoin',
  SFE: 'Safecoin',
  ARDR: 'Ardor',
  BS: 'BlackShadowCoin',
  JIF: 'JiffyCoin',
  CRAB: 'CrabCoin',
  'AIR*': 'Aircoin',
  HILL: 'President Clinton',
  FOREX: 'ForexCoin',
  MONETA: 'Moneta',
  EC: 'Eclipse',
  RUBIT: 'Rublebit',
  HCC: 'HappyCreatorCoin ',
  BRAIN: 'BrainCoin',
  VTX: 'Vertex',
  KRC: 'KRCoin',
  ROYAL: 'RoyalCoin',
  LFC: 'BigLifeCoin',
  ZUR: 'Zurcoin',
  NUBIS: 'NubisCoin',
  TENNET: 'Tennet',
  PEC: 'PeaceCoin',
  GMX: 'Goldmaxcoin',
  '32BIT': '32Bitcoin',
  GNJ: 'GanjaCoin V2',
  TEAM: 'TeamUP',
  SCT: 'ScryptToken',
  LANA: 'LanaCoin',
  ELE: 'Elementrem',
  GCC: 'GuccioneCoin',
  AND: 'AndromedaCoin',
  GBYTE: 'Byteball',
  EQUAL: 'EqualCoin',
  SWEET: 'SweetStake',
  '2BACCO': '2BACCO Coin',
  DKC: 'DarkKnightCoin',
  COC: 'Community Coin',
  CHOOF: 'ChoofCoin',
  CSH: 'CashOut',
  ZCL: 'ZClassic',
  RYCN: 'RoyalCoin 2.0',
  PCS: 'Pabyosi Coin',
  NBIT: 'NetBit',
  WINE: 'WineCoin',
  DAR: 'Darcrus',
  ARK: 'ARK',
  IFLT: 'InflationCoin',
  ZECD: 'ZCashDarkCoin',
  ZXT: 'Zcrypt',
  WASH: 'WashingtonCoin',
  TESLA: 'TeslaCoilCoin',
  LUCKY: 'LuckyBlocks (LUCKY)',
  VSL: 'vSlice',
  TPG: 'Troll Payment',
  LEO: 'LEOcoin',
  MDT: 'Midnight ',
  CBD: 'CBD Crystals',
  PEX: 'PosEx',
  INSANE: 'InsaneCoin',
  GNT: 'Golem Network Token',
  PEN: 'PenCoin',
  BASH: 'LuckChain',
  FAME: 'FameCoin',
  LIV: 'LiviaCoin',
  SP: 'Sex Pistols',
  MEGA: 'MegaFlash',
  VRS: 'Veros',
  ALC: 'Arab League Coin',
  DOGETH: 'EtherDoge',
  KLC: 'KiloCoin',
  HUSH: 'Hush',
  BTLC: 'BitLuckCoin',
  DRM8: 'Dream8Coin',
  FIST: 'FistBump',
  EBZ: 'Ebitz',
  DRS: 'Digital Rupees',
  FGZ: 'Free Game Zone',
  BOSON: 'BosonCoin',
  ATX: 'ArtexCoin',
  PNC: 'PlatiniumCoin',
  BRDD: 'BeardDollars',
  TIME: 'Time',
  BIP: 'BipCoin',
  XNC: 'XenCoin',
  EMB: 'EmberCoin',
  BTTF: 'Coin to the Future',
  DLR: 'DollarOnline',
  CSMIC: 'Cosmic',
  FIRST: 'FirstCoin',
  SCASH: 'SpaceCash',
  XEN: 'XenixCoin',
  JIO: 'JIO Token',
  IW: 'iWallet',
  JNS: 'Janus',
  TRICK: 'TrickyCoin',
  DCRE: 'DeltaCredits',
  FRE: 'FreeCoin',
  NPC: 'NPCcoin',
  PLNC: 'PLNCoin',
  DGMS: 'Digigems',
  ICOB: 'Icobid',
  ARCO: 'AquariusCoin',
  KURT: 'Kurrent',
  XCRE: 'Creatio',
  ENT: 'Eternity',
  UR: 'UR',
  MTLM3: 'Metal Music v3',
  ODNT: 'Old Dogs New Tricks',
  EUC: 'Eurocoin',
  CCX: 'CoolDarkCoin',
  BCF: 'BitcoinFast',
  SEEDS: 'SeedShares',
  POSW: 'PoSWallet',
  TKS: 'Tokes',
  BCCOIN: 'BitConnect Coin',
  SHORTY: 'ShortyCoin',
  PCM: 'Procom',
  KC: 'Kernalcoin',
  CORAL: 'CoralPay',
  BamitCoin: 'BAM',
  NXC: 'Nexium',
  MONEY: 'MoneyCoin',
  BSTAR: 'Blackstar',
  HSP: 'Horse Power',
  HZT: 'HazMatCoin',
  CS: 'CryptoSpots',
  XSP: 'PoolStamp',
  CCRB: 'CryptoCarbon',
  BULLS: 'BullshitCoin',
  INCNT: 'Incent',
  ICON: 'Iconic',
  NIC: 'NewInvestCoin',
  ACN: 'AvonCoin',
  XNG: 'Enigma',
  XCI: 'Cannabis Industry Coin',
  LOOK: 'LookCoin',
  LOC: 'Loco',
  MMXVI: 'MMXVI',
  TRST: 'TrustCoin',
  MIS: 'MIScoin',
  WOP: 'WorldPay',
  CQST: 'ConquestCoin',
  IMPS: 'Impulse Coin',
  IN: 'InCoin',
  CHIEF: 'TheChiefCoin',
  GOAT: 'Goat',
  ANAL: 'AnalCoin',
  RC: 'Russiacoin',
  PND: 'PandaCoin',
  PX: 'PXcoin',
  'CND*': 'Canada eCoin',
  OPTION: 'OptionCoin',
  AV: 'Avatar Coin',
  LTD: 'Limited Coin',
  UNITS: 'GameUnits',
  HEEL: 'HeelCoin',
  GAKH: 'GAKHcoin',
  SHIFT: 'Shift',
  S8C: 'S88 Coin',
  LVG: 'Leverage Coin',
  DRA: 'DraculaCoin',
  ASAFE2: 'Allsafe',
  LTCR: 'LiteCreed',
  QBC: 'Quebecoin',
  XPRO: 'ProCoin',
  'AST*': 'Astral',
  GIFT: 'GiftNet',
  VIDZ: 'PureVidz',
  INC: 'Incrementum',
  PTA: 'PentaCoin',
  ACID: 'AcidCoin',
  ZLQ: 'ZLiteQubit',
  RADI: 'RadicalCoin',
  RNC: 'ReturnCoin',
  GOLOS: 'Golos',
  PASC: 'Pascal Coin',
  TWIST: 'TwisterCoin',
  PAYP: 'PayPeer',
  DETH: 'DarkEther',
  YAY: 'YAYcoin',
  YES: 'YesCoin',
  LENIN: 'LeninCoin',
  MRSA: 'MrsaCoin',
  OS76: 'OsmiumCoin',
  BOSS: 'BitBoss',
  BIC: 'Bikercoins',
  CRPS: 'CryptoPennies',
  MOTO: 'Motocoin',
  NTCC: 'NeptuneClassic',
  'XNC*': 'Numismatic Collections',
  HXX: 'HexxCoin',
  SPKTR: 'Ghost Coin',
  MAC: 'MachineCoin',
  SEL: 'SelenCoin',
  NOO: 'Noocoin',
  CHAO: '23 Skidoo',
  YMC: 'YamahaCoin',
  JOK: 'JokerCoin',
  GBIT: 'GravityBit',
  TEC: 'TeCoin',
  BOMB: 'BombCoin',
  RIDE: 'Ride My Car',
  PIVX: 'Private Instant Verified Transaction',
  KED: 'Klingon Empire Darsek',
  CNO: 'Coino',
  WEALTH: 'WealthCoin',
  IOP: 'Internet of People',
  XSPEC: 'Spectre',
  PEPECASH: 'Pepe Cash',
  CLICK: 'Clickcoin',
  ELS: 'Elysium',
  KUSH: 'KushCoin',
  ERY: 'Eryllium',
  PLU: 'Pluton',
  PRES: 'President Trump',
  BTZ: 'BitzCoin',
  OPES: 'Opes',
  WCT: 'Waves Community Token',
  UBQ: 'Ubiq',
  RATIO: 'Ratio',
  BAN: 'Babes and Nerds',
  NICE: 'NiceCoin',
  SMF: 'SmurfCoin',
  CWXT: 'CryptoWorldXToken',
  TECH: 'TechCoin',
  CIR: 'CircuitCoin',
  LEPEN: 'LePenCoin',
  ROUND: 'RoundCoin',
  MAR: 'MarijuanaCoin',
  MARX: 'MarxCoin',
  TAT: 'Tatiana Coin',
  HAZE: 'HazeCoin',
  PRX: 'Printerium',
  NRC: 'Neurocoin',
  PAC: 'PacCoin',
  IMPCH: 'Impeach',
  ERR: 'ErrorCoin',
  TIC: 'TrueInvestmentCoin',
  NUKE: 'NukeCoin',
  EOC: 'EveryonesCoin',
  SFC: 'Solarflarecoin',
  JANE: 'JaneCoin',
  PARA: 'ParanoiaCoin',
  MM: 'MasterMint',
  BXC: 'Bitcedi',
  NDOGE: 'NinjaDoge',
  ZBC: 'Zilbercoin',
  MLN: 'Melon',
  PAY: 'TenX',
  ORO: 'OroCoin',
  ALEX: 'Alexandrite',
  TBCX: 'TrashBurn',
  MCAR: 'MasterCar',
  THS: 'TechShares',
  ACES: 'AcesCoin',
  UAEC: 'United Arab Emirates Coin',
  EA: 'EagleCoin',
  CREA: 'CreativeChain',
  WISC: 'WisdomCoin',
  BVC: 'BeaverCoin',
  FIND: 'FindCoin',
  MLITE: 'MeLite',
  STALIN: 'StalinCoin',
  TSE: 'TattooCoin',
  VLTC: 'VaultCoin',
  BIOB: 'BioBar',
  SWT: 'Swarm City Token',
  PASL: 'Pascal Lite',
  ZER: 'Zero',
  CHAT: 'ChatCoin',
  CDN: 'Canada eCoin',
  TPAY: 'TrollPlay',
  NETKO: 'Netko',
  ZOI: 'Zoin',
  HONEY: 'Honey',
  MXT: 'MartexCoin',
  DTB: 'Databits',
  VEG: 'BitVegan',
  MBIT: 'Mbitbooks',
  VOLT: 'BitVolt',
  MGO: 'MobileGo',
  EDG: 'Edgeless',
  'B@': 'BankCoin',
  BEST: 'BestChain',
  CHC: 'ChainCoin',
  ZENI: 'Zennies',
  PLANET: 'PlanetCoin',
  DUCK: 'DuckDuckCoin',
  BNX: 'BnrtxCoin',
  BSTK: 'BattleStake',
  RNS: 'RenosCoin',
  DBIX: 'DubaiCoin',
  AMIS: 'AMIS',
  KAYI: 'Kayı',
  XVP: 'VirtacoinPlus',
  BOAT: 'Doubloon',
  TAJ: 'TajCoin',
  IMX: 'Impact',
  CJC: 'CryptoJournal',
  AMY: 'Amygws',
  QBT: 'Cubits',
  'SRC*': 'StarCredits',
  EB3: 'EB3coin',
  XVE: 'The Vegan Initiative',
  FAZZ: 'FazzCoin',
  APT: 'Aptcoin',
  BLAZR: 'BlazerCoin',
  ARPA: 'ArpaCoin',
  'BNB*': 'Boats and Bitches',
  UNI: 'Universe',
  ECO: 'ECOcoin',
  XLR: 'Solaris',
  DARK: 'Dark',
  DON: 'DonationCoin',
  MER: 'Mercury',
  WGO: 'WavesGO',
  RLC: 'iEx.ec',
  ATMS: 'Atmos',
  INPAY: 'InPay',
  ETT: 'EncryptoTel',
  WBTC: 'wBTC',
  VISIO: 'Visio',
  HPC: 'HappyCoin',
  GOT: 'Giotto Coin',
  CXT: 'Coinonat',
  EMPC: 'EmporiumCoin',
  GNO: 'Gnosis',
  LGD: 'Legends Cryptocurrency',
  TAAS: 'Token as a Service',
  BUCKS: 'SwagBucks',
  XBY: 'XtraBYtes',
  GUP: 'Guppy',
  MCRN: 'MacronCoin',
  LUN: 'Lunyr',
  RAIN: 'Condensate',
  WSX: 'WeAreSatoshi',
  IEC: 'IvugeoEvolutionCoin',
  IMS: 'Independent Money System',
  ARGUS: 'ArgusCoin',
  CNT: 'Centurion',
  LMC: 'LomoCoin',
  TKN: 'TokenCard  ',
  BTCS: 'Bitcoin Scrypt',
  PROC: 'ProCurrency',
  XGR: 'GoldReserve',
  'WRC*': 'WarCoin',
  BENJI: 'BenjiRolls',
  HMQ: 'Humaniq',
  DUO: 'ParallelCoin',
  RBX: 'RiptoBuX',
  GRW: 'GrowthCoin',
  APX: 'Apx',
  MILO: 'MiloCoin',
  OLV: 'OldV',
  ILC: 'ILCoin',
  MRT: 'MinersReward',
  IOU: 'IOU1',
  PZM: 'Prizm',
  PHR: 'Phreak',
  ANT: 'Aragon',
  PUPA: 'PupaCoin',
  RICE: 'RiceCoin',
  XCT: 'C-Bits',
  DEA: 'Degas Coin',
  RED: 'Redcoin',
  ZSE: 'ZSEcoin',
  CTIC: 'Coinmatic',
  TAP: 'TappingCoin',
  BITOK: 'BitOKX',
  PBT: 'Primalbase',
  MUU: 'MilkCoin',
  INF8: 'Infinium-8',
  HTML5: 'HTML Coin',
  MNE: 'Minereum',
  DICE: 'Etheroll',
  'SUB*': 'Subscriptio',
  USC: 'Ultimate Secure Cash',
  DUX: 'DuxCoin',
  XPS: 'PoisonIvyCoin',
  EQT: 'EquiTrader',
  INSN: 'Insane Coin',
  BAT: 'Basic Attention Token',
  'MAT*': 'Manet Coin',
  F16: 'F16Coin',
  HAMS: 'HamsterCoin',
  QTUM: 'Quantum',
  NEF: 'NefariousCoin',
  ZEN: 'ZenCash',
  BOS: 'BOScoin',
  QWARK: 'Qwark',
  IOT: 'IOTA',
  QRL: 'Quantum Resistant Ledger',
  ADL: 'Adelphoi',
  ECC: 'E-CurrencyCoin',
  PTOY: 'Patientory',
  ZRC: 'ZrCoin',
  LKK: 'Lykke',
  ESP: 'Espers',
  MAD: 'SatoshiMadness',
  DYN: 'Dynamic',
  SEQ: 'Sequence',
  MCAP: 'MCAP',
  MYST: 'Mysterium',
  VERI: 'Veritaseum',
  SNM: 'SONM',
  SKY: 'Skycoin',
  CFI: 'Cofound.it',
  SNT: 'Status Network Token',
  AVT: 'AventCoin',
  CVC: 'Civic',
  IXT: 'iXledger',
  BQX: 'Ethos',
  STA: 'Starta',
  EFYT: 'Ergo',
  XTZ: 'Tezos',
  MCO: 'Monaco',
  NMR: 'Numerai',
  ADX: 'AdEx',
  ECOB: 'EcoBit',
  PLBT: 'Polybius',
  USDT: 'Tether',
  XRB: 'RaiBlocks',
  AHT: 'Ahoolee',
  ATB: 'ATB coin',
  TIX: 'Blocktix',
  '4CHN': 'ChanCoin',
  CMP: 'Compcoin',
  RVT: 'Rivetz',
  'NET*': 'Nimiq Exchange Token',
  '8BT': '8 Circuit Studios',
  CDT: 'CoinDash',
  ACT: 'ACT',
  DNT: 'district0x',
  SUR: 'Suretly',
  MIV: 'MakeItViral',
  'BET*': 'DAO.casino',
  SAN: 'Santiment',
  WGR: 'Wagerr',
  XEL: 'Elastic',
  NVST: 'NVO',
  FUN: 'FunFair',
  FUNC: 'FunCoin',
  PQT: 'PAquarium',
  WTT: 'Giga Watt',
  MTL: 'Metal',
  HVN: 'Hive',
  MYB: 'MyBit',
  PPT: 'Populous',
  SNC: 'SunContract',
  COR: 'Corion',
  XRL: 'Rialto.AI',
  OROC: 'Orocrypt',
  OAX: 'OpenANX',
  MBI: 'Monster Byte Inc',
  DDF: 'Digital Developers Fund',
  DIM: 'DIMCOIN',
  GGS: 'Gilgam',
  DNA: 'Encrypgen',
  FND: 'FundRequest',
  DCY: 'Dinastycoin',
  CFT: 'CryptoForecast',
  DNR: 'Denarius',
  DP: 'DigitalPrice',
  VUC: 'Virta Unique Coin',
  BTPL: 'Bitcoin Planet',
  UNIFY: 'Unify',
  IPC: 'ImperialCoin',
  BRIT: 'BritCoin',
  AMMO: 'Ammo Rewards',
  SOCC: 'SocialCoin',
  MASS: 'Mass.Cloud',
  LA: 'LAToken',
  IML: 'IMMLA',
  XUC: 'Exchange Union',
  STU: 'BitJob',
  PLR: 'Pillar',
  GUNS: 'GeoFunders',
  IFT: 'InvestFeed',
  'CAT*': 'BitClave',
  PRO: 'Propy',
  SYC: 'SynchroCoin',
  IND: 'Indorse',
  'AHT*': 'Bowhead Health',
  TRIBE: 'TribeToken',
  ZRX: '0x',
  TNT: 'Tierion',
  'PRE*': 'Presearch',
  COSS: 'COSS',
  STORM: 'Storm',
  NPX: 'Napoleon X',
  STORJ: 'Storj',
  SCORE: 'Scorecoin',
  OMG: 'OmiseGo',
  OTX: 'Octanox',
  EQB: 'Equibit',
  VOISE: 'Voise',
  ETBS: 'EthBits',
  CVCOIN: 'Crypviser',
  DRP: 'DCORP',
  ARC: 'ArcticCoin',
  BOG: 'Bogcoin',
  NDC: 'NeverDie',
  POE: 'Po.et',
  ADT: 'AdToken',
  AE: 'Aeternity',
  UET: 'Useless Ethereum Token',
  PART: 'Particl',
  AGRS: 'Agoras Token',
  SAND: 'BeachCoin',
  'XAI*': 'AICoin',
  DMT: 'DMarket',
  DAS: 'DAS',
  ADST: 'Adshares',
  XCJ: 'CoinJob',
  RKC: 'Royal Kingdom Coin',
  NLC2: 'NoLimitCoin',
  LINDA: 'Linda',
  SPN: 'Spoon',
  KING: 'King93',
  ANCP: 'Anacrypt',
  RCC: 'Reality Clash',
  ROOTS: 'RootProject',
  SNK: 'Sosnovkino',
  CABS: 'CryptoABS',
  OPT: 'Opus',
  ZNT: 'OpenZen',
  BITSD: 'Bits Digit',
  XLC: 'LeviarCoin',
  SKIN: 'Skincoin',
  MSP: 'Mothership',
  HIRE: 'HireMatch',
  'BBT*': 'BrickBlock',
  DFBT: 'DentalFix',
  EQ: 'EQUI',
  WOLK: 'Wolk',
  VIB: 'Viberate',
  ONION: 'DeepOnion',
  BTX: 'Bitcore',
  ICE: 'iDice',
  XID: 'Sphre AIR',
  GCN: 'GCoin',
  'ATOM*': 'Cosmos',
  MANA: 'Decentraland',
  ICOO: 'ICO OpenLedger',
  TME: 'Timereum',
  SMART: 'SmartCash',
  SIGT: 'Signatum',
  ONX: 'Onix',
  COE: 'CoEval',
  ARENA: 'Arena',
  WINK: 'Wink',
  CRM: 'Cream',
  BCH: 'Bitcoin Cash / BCC',
  DGPT: 'DigiPulse',
  MOBI: 'Mobius',
  CSNO: 'BitDice',
  KICK: 'KickCoin',
  SDAO: 'Solar DAO',
  STX: 'Stox',
  BNB: 'Binance Coin',
  CORE: 'Core Group Asset',
  KCN: 'Kencoin',
  AUT: 'Autoria',
  CTT: 'CodeTract',
  GRWI: 'Growers International',
  MNY: 'Monkey',
  MTH: 'Monetha',
  CCC: 'CCCoin',
  UMC: 'Umbrella Coin',
  BMXT: 'Bitmxittz',
  CC: 'CyberCoin',
  GAS: 'Gas',
  FIL: 'FileCoin',
  OCL: 'Oceanlab',
  BNC: 'Benjacoin',
  TOM: 'Tomahawkcoin',
  'BTM*': 'Bytom',
  XAS: 'Asch',
  SMNX: 'SMNX',
  DCN: 'Dentacoin',
  DLT: 'Agrello Delta',
  MRV: 'Macroverse',
  MBRS: 'Embers',
  SUB: 'Substratum Network',
  MET: 'Memessenger',
  NEBL: 'Neblio',
  PGL: 'Prospectors',
  XMCC: 'MonacoCoin',
  AUTH: 'Authoreon',
  'CASH*': 'Cash Poker Pro',
  DTCT: 'DetectorToken',
  CTR: 'Centra',
  WNET: 'Wavesnode.net',
  PRG: 'Paragon',
  THNX: 'ThankYou',
  WORM: 'HealthyWorm',
  FUCK: 'Fuck Token',
  VNT: 'Veredictum',
  IGNIS: 'Ignis',
  IWT: 'IwToken',
  JDC: 'JustDatingSite',
  EVX: 'Everex',
  ICOS: 'ICOBox',
  PIX: 'Lampix',
  LTA: 'Litra',
  NIMFA: 'Nimfamoney',
  SCOR: 'Scorista',
  MLS: 'CPROP',
  KEX: 'KexCoin',
  BRO: 'Bitradio',
  MINEX: 'Minex',
  ATL: 'ATLANT',
  'ARI*': 'BeckSang',
  'MAG*': 'Magos',
  DFT: 'Draftcoin',
  VEN: 'Vechain',
  UTK: 'Utrust',
  LAT: 'Latium',
  SOJ: 'Sojourn Coin',
  STCN: 'Stakecoin',
  SQP: 'SqPay',
  RIYA: 'Etheriya',
  AMB: 'Ambrosus',
  WAN: 'Wanchain',
  MNT: 'GoldMint',
  ALTOCAR: 'AltoCar',
  'CFT*': 'Credo',
  BLX: 'Blockchain Index',
  BOU: 'Boulle',
  OXY: 'Oxycoin',
  TTT: 'Tap Project',
  AMT: 'Acumen',
  NYC: 'NewYorkCoin',
  FRAZ: 'FrazCoin',
  GXC: 'Gx Coin',
  KRONE: 'Kronecoin',
  SRT: 'Scrypto',
  AVA: 'Avalon',
  BT: 'BuildTeam',
  ACC: 'AdCoin',
  'AR*': 'Ar.cash',
  Z2: 'Z2 Coin',
  LINX: 'Linx',
  XCXT: 'CoinonatX',
  BLAS: 'BlakeStar',
  GOOD: 'GoodCoin',
  SCL: 'Social Nexus',
  TRV: 'Travel Coin',
  CRTM: 'Cryptum',
  EON: 'Exscudo',
  PST: 'Primas',
  MTX: 'Matryx',
  PRIX: 'Privatix',
  CTX: 'CarTaxi',
  ENJ: 'Enjin Coin',
  CNX: 'Cryptonex',
  DRC: 'Dropcoin',
  FUEL: 'Etherparty',
  ACE: 'TokenStars',
  WTC: 'Waltonchain',
  BRX: 'Breakout Stake',
  WRT: 'WRTcoin',
  ORME: 'Ormeus Coin',
  DEEP: 'Deep Gold',
  TMT: 'ToTheMoon',
  'CCT*': 'Crystal Clear Token ',
  WSH: 'Wish Finance',
  'ARNA*': 'ARNA Panacea',
  ABC: 'AB-Chain',
  PRP: 'Papyrus',
  BMC: 'Blackmoon Crypto',
  'SKR*': 'Skrilla Token',
  '3DES': '3DES',
  PYN: 'Paycentos',
  KAPU: 'Kapu',
  SENSE: 'Sense Token',
  FC: 'Facecoin',
  RCN: 'Ripio',
  NRN: 'Doc.ai Neuron',
  LINK: 'ChainLink',
  EDO: 'Eidoo',
  ATKN: 'A-Token',
  KNC: 'Kyber Network',
  RUSTBITS: 'Rustbits',
  REX: 'REX',
  ETHD: 'Ethereum Dark',
  SUMO: 'Sumokoin',
  TRX: 'Tron',
  '8S': 'Elite 888',
  TKT: 'Crypto Tickets',
  RHEA: 'Rhea',
  ART: 'Maecenas',
  DRT: 'DomRaider',
  DTT: 'DreamTeam Token',
  MTN: 'TrackNetToken',
  STOCKBET: 'StockBet',
  PLM: 'Algo.Land',
  FDC: 'FoodCoin',
  SALT: 'Salt Lending',
  XP: 'XP',
  LRC: 'Loopring',
  HSR: 'Hshare',
  GLA: 'Gladius',
  ZNA: 'Zenome',
  EZM: 'EZMarket',
  ODN: 'Obsidian',
  POLL: 'ClearPoll',
  MTK: 'Moya Token',
  CAS: 'Cashaa',
  GJC: 'Global Jobcoin',
  WIC: 'Wi Coin',
  WAND: 'WandX',
  ELIX: 'Elixir',
  HAC: 'Hackspace Capital',
  ADA: 'Cardano',
  YOYOW: 'Yoyow',
  REC: 'Regalcoin',
  BIS: 'Bismuth',
  OPP: 'Opporty',
  ROCK: 'Ice Rock Mining',
  ICX: 'ICON Project',
  VSX: 'Vsync',
  FLASH: 'FLASH coin',
  GRF: 'Graft Network',
  BTCZ: 'BitcoinZ',
  PPP: 'PayPie',
  GUESS: 'Peerguess',
  ETP: 'Metaverse',
  CIX: 'Cryptonetix',
  ERT: 'Esports.com',
  'BAC*': 'LakeBanker',
  FLIK: 'FLiK',
  TRIP: 'Trippki',
  MBT: 'Multibot',
  JVY: 'Javvy',
  ALIS: 'ALISmedia',
  LEV: 'Leverj',
  ARBI: 'Arbi',
  ELT: 'Eloplay',
  REQ: 'Request Network',
  ARN: 'Aeron',
  DAT: 'Datum',
  VIBE: 'VIBEHub',
  ROK: 'Rockchain',
  XRED: 'X Real Estate Development',
  DAY: 'Chronologic',
  AST: 'AirSwap',
  HXT: 'HextraCoin',
  CND: 'Cindicator',
  'VRP*': 'Prosense.tv',
  NTM: 'NetM',
  TZC: 'TrezarCoin',
  ENG: 'Enigma',
  MCI: 'Musiconomi',
  WAX: 'Worldwide Asset eXchange',
  AIR: 'AirToken',
  NTO: 'Fujinto',
  ATCC: 'ATC Coin',
  KOLION: 'Kolion',
  WILD: 'Wild Crypto',
  ELTC2: 'eLTC',
  POWR: 'Power Ledger',
  C20: 'Crypto20',
  RYZ: 'Anryze',
  'GXC*': 'GenXCoin',
  ELM: 'Elements',
  TER: 'TerraNovaCoin',
  XCS: 'CybCSec Coin',
  BQ: 'Bitqy',
  EVR: 'Everus',
  TOA: 'TOA Coin',
  MNZ: 'Monaize',
  VIVO: 'VIVO Coin',
  RPX: 'Red Pulse',
  MDA: 'Moeda',
  ZSC: 'Zeusshield',
  AURS: 'Aureus',
  CAG: 'Change',
  PKT: 'Playkey',
  ECHT: 'e-Chat',
  INXT: 'Internxt',
  ATS: 'Authorship',
  RGC: 'RG Coin',
  EBET: 'EthBet',
  R: 'Revain',
  MOD: 'Modum',
  'BM*': 'Bitcomo',
  CPAY: 'CryptoPay',
  RUP: 'Rupee',
  'BON*': 'Bonpay',
  WHL: 'WhaleCoin',
  BTG: 'Bitcoin Gold',
  UP: 'UpToken',
  ETG: 'Ethereum Gold',
  WOMEN: 'WomenCoin',
  MAY: 'Theresa May Coin',
  RNDR: 'Render Token',
  EDDIE: 'Eddie coin',
  'SCT*': 'Soma',
  NAMO: 'NamoCoin',
  KCS: 'Kucoin',
  GAT: 'GATCOIN',
  BLUE: 'Ethereum Blue',
  FLLW: 'Follow Coin',
  WYR: 'Wyrify',
  VZT: 'Vezt',
  INDI: 'IndiCoin',
  LUX: 'LUXCoin',
  PIRL: 'Pirl',
  ECASH: 'Ethereum Cash',
  DRGN: 'Dragonchain',
  BRAT: 'Brat',
  DTR: 'Dynamic Trading Rights',
  TKR: 'CryptoInsight',
  ELITE: 'EthereumLite',
  XIOS: 'Xios',
  DOVU: 'DOVU',
  XNN: 'Xenon',
  BTDX: 'Bitcloud 2.0',
  'LOAN*': 'Lendoit',
  ZAB: 'ZABERcoin',
  MDL: 'Modulum',
  BT1: 'Bitfinex Bitcoin Future',
  BT2: 'Bitcoin SegWit2X',
  SHP: 'Sharpe Capital',
  JCR: 'Jincor',
  XSB: 'Extreme Sportsbook',
  EBST: 'eBoost',
  KEK: 'KekCoin',
  AID: 'AidCoin',
  'BHC*': 'BlackholeCoin',
  ALTCOM: 'AltCommunity Coin',
  DATA: 'Streamr DATAcoin',
  UGT: 'ugChain',
  DTC: 'Datacoin',
  PLAY: 'HEROcoin',
  PURE: 'Pure',
  CLD: 'Cloud',
  OTN: 'Open Trading Network',
  POS: 'PoSToken',
  REBL: 'Rebellious',
  EXN: 'ExchangeN',
  TRCT: 'Tracto',
  UKG: 'UnikoinGold',
  BTCRED: 'Bitcoin Red',
  EBCH: 'eBitcoinCash',
  'JPC*': 'J Coin',
  AXT: 'AIX',
  'RDN*': 'Raiden Network',
  RUPX: 'Rupaya',
  BDR: 'BlueDragon',
  XIN: 'Infinity Economics',
  DUTCH: 'Dutch Coin',
  'HNC*': 'Huncoin',
  'MDC*': 'MadCoin',
  PURA: 'Pura',
  INN: 'Innova',
  HST: 'Decision Token',
  BCPT: 'BlockMason Credit Protocol',
  BDL: 'Bitdeal',
  CMS: 'COMSA',
  XBL: 'Billionaire Token',
  ZEPH: 'Project Zephyr',
  GES: 'Galaxy eSolutions',
  NULS: 'Nuls',
  'PHR*': 'Phore',
  LCASH: 'LitecoinCash',
  CFD: 'Confido',
  WSC: 'WiserCoin',
  DBET: 'Decent.bet',
  xGOx: 'Go!',
  NEWB: 'Newbium',
  LIFE: 'LIFE',
  CREDO: 'Credo',
  MSR: 'Masari',
  'ESC*': 'Ethersportcoin',
  BNK: 'Bankera',
  ELLA: 'Ellaism',
  BPL: 'BlockPool',
  COIN: 'Coinvest',
  DRXNE: 'Droxne',
  SKR: 'Sakuracoin',
  GRID: 'Grid+',
  XPTX: 'PlatinumBAR',
  GVT: 'Genesis Vision',
  ETK: 'Energi Token',
  ASTRO: 'Astronaut',
  GMT: 'Mercury Protocol',
  'EPY*': 'Emphy',
  SOAR: 'Soarcoin',
  EXY: 'Experty',
  HOLD: 'Interstellar Holdings',
  MNX: 'MinexCoin',
  CRDS: 'Credits',
  VIU: 'Viuly',
  SCR: 'Scorum',
  ABT: 'Advanced Browsing Token',
  GFT: 'Giftcoin',
  STC: 'StarterCoin',
  QSP: 'Quantstamp',
  RIPT: 'RiptideCoin',
  BBT: 'BitBoost',
  GBX: 'GoByte',
  CSTL: 'Castle',
  ICC: 'Insta Cash Coin',
  JNT: 'Jibrel Network Token',
  QASH: 'Quoine Liquid',
  ALQO: 'Alqo',
  'KNC**': 'KingN Coin',
  TRIA: 'Triaconta',
  PBL: 'Publica',
  MAG: 'Magnet',
  STEX: 'STEX',
  UFR: 'Upfiring',
  TAU: 'Lamden Tau',
  LAB: 'Labrys',
  FLIXX: 'Flixxo',
  FRD: 'Farad',
  PFR: 'PayFair',
  ECA: 'Electra',
  LDM: 'Ludum token',
  LTG: 'LiteCoin Gold',
  BCD: 'Bitcoin Diamond',
  STP: 'StashPay',
  SPANK: 'SpankChain',
  'WISH*': 'MyWish',
  AERM: 'Aerium',
  PLX: 'PlexCoin',
  NIO: 'Autonio',
  ETHB: 'EtherBTC',
  'CDX*': 'Commodity Ad Network',
  FOOD: 'FoodCoin',
  'DRC*': 'Darico',
  VOT: 'Votecoin',
  UQC: 'Uquid Coin',
  LEND: 'EthLend',
  SETH: 'Sether',
  'TIO*': 'Tio Tour Guides',
  XSH: 'SHIELD',
  'BCD*': 'BitCAD',
  'BCO*': 'BridgeCoin',
  ONG: 'onG.social',
  PRL: 'Oyster Pearl',
  BTCM: 'BTCMoon',
  ETBT: 'Ethereum Black',
  ZCG: 'ZCashGOLD',
  MUT: 'Mutual Coin',
  AION: 'Aion',
  MEOW: 'Kittehcoin',
  DIVX: 'Divi',
  CNBC: 'Cash & Back Coin',
  RHOC: 'RChain',
  'ARC*': ' Arcade City',
  XUN: 'UltraNote',
  RFL: 'RAFL',
  ELTCOIN: 'ELTCOIN',
  GRX: 'Gold Reward Token',
  NTK: 'Neurotoken',
  ERO: 'Eroscoin',
  'CMT*': 'CyberMiles',
  RLX: 'Relex',
  MAN: 'People',
  CWV: 'CryptoWave',
  'ACT*': 'Achain',
  NRO: 'Neuro',
  SEND: 'Social Send',
  GLT: 'GlobalToken',
  X8X: 'X8Currency',
  COAL: 'BitCoal',
  DAXX: 'DaxxCoin',
  BWK: 'Bulwark',
  FNT: 'FinTab',
  BTCE: 'EthereumBitcoin',
  FYP: 'FlypMe',
  BOXY: 'BoxyCoin',
  UTN: 'Universa',
  DPP: 'Digital Assets Power Play',
  ADB: 'Adbank',
  XDC: 'XinFin Coin',
  BIO: 'Biocoin',
  BTCL: 'BTC Lite',
  PCN: 'PeepCoin',
  MUSIC: 'Musicoin',
  TGT: 'TargetCoin',
  BMT: 'BMChain',
  CJT: 'ConnectJob Token',
  STH: 'SmartHoldem',
  PYP: 'PayPro',
  XMRG: 'Monero Gold',
  WPR: 'WePower',
  XGB: 'GoldenBird',
  COB: 'Cobinhood',
  DENT: 'Dent',
  VEE: 'BLOCKv',
  BCAP: 'Blockchain Capital',
  MKR: 'Maker',
  HGT: 'Hello Gold',
  CAPP: 'Cappasity',
  TFL: 'True Flip Lottery',
  STAR: 'Starbase',
  HDG: 'Hedge Token',
  FYN: 'FundYourselfNow',
  HBT: 'Hubiit',
  SIFT: 'Smart Investment Fund Token',
  RBTC: 'Bitcoin Revolution',
  GIM: 'Gimli',
  TIE: 'Ties Network',
  H2O: 'Hydrominer',
  EVC: 'Eventchain',
  EGAS: 'ETHGAS',
  CASH: 'CashCoin',
  BTE: 'ByteCoin',
  WABI: 'WaBi',
  KIN: 'Kin',
  LNK: 'Ethereum.Link',
  EARTH: 'Earth Token',
  ILCT: 'ILCoin Token',
  'ROCK*': 'RocketCoin ',
  NGC: 'NagaCoin',
  SPHTX: 'SophiaTX',
  CLOUT: 'Clout',
  CMPCO: 'CampusCoin',
  MEDI: 'MediBond',
  NEOG: 'NEO Gold',
  EMT: 'EasyMine',
  CRED: 'Verify',
  ABYSS: 'The Abyss',
  PING: 'CryptoPing',
  RPC: 'RonPaulCoin',
  ITT: 'Intelligent Trading Technologies',
  PIE: 'Persistent Information Exchange',
  MAT: 'MiniApps',
  CZC: 'Crazy Coin',
  TIO: 'Trade.io',
  ATFS: 'ATFS Project',
  SBTC: 'Super Bitcoin',
  KLK: 'Kalkulus',
  AC3: 'AC3',
  GTO: 'GIFTO',
  TNB: 'Time New Bank',
  'CHIPS*': 'CHIPS',
  HKN: 'Hacken',
  B2B: 'B2B',
  'LOC*': 'LockChain',
  'PTC*': 'Propthereum',
  WEB: 'Webcoin',
  ITNS: 'IntenseCoin',
  SNOV: 'Snovio',
  SND: 'Sandcoin',
  QVT: 'Qvolta',
  REAL: 'REAL',
  HRB: 'Harbour DAO',
  LBTC: 'LiteBitcoin',
  FRST: 'FirstCoin',
  WRC: 'Worldcore',
  'SMT*': 'SmartMesh',
  COFI: 'CoiniFi',
  DBR: 'Düber',
  MTRC: 'ModulTrade',
  FLP: 'Gameflip',
  WIZ: 'Crowdwiz',
  CAV: 'Caviar',
  BAR: 'TBIS token',
  'KEY*': 'SelfKey',
  'MNT*': 'Media Network Coin',
  'DTT*': 'Data Trading',
  GEA: 'Goldea',
  EOS: 'EOS',
  UNB: 'UnbreakableCoin',
  APPC: 'AppCoins',
  AVE: 'Avesta',
  SMT: 'Social Media Market',
  DEB: 'Debitum Token',
  INS: 'INS Ecosystem',
  SRN: 'SirinLabs',
  REA: 'Realisto',
  'CAN*': 'CanYaCoin',
  BKX: 'BANKEX',
  BDG: 'BitDegree',
  LOCI: 'LociCoin',
  ODMC: 'ODMCoin',
  'CABS*': 'CyberTrust',
  'XUC*': 'UCash',
  EVN: 'Envion',
  COV: 'Covesting',
  OST: 'SimpleToken',
  ETN: 'Electroneum',
  LTCU: 'LiteCoin Ultra',
  EMGO: 'MobileGo',
  EBTC: 'eBitcoin',
  BTCA: 'Bitair',
  NEU: 'Neumarks',
  'NEU*': 'NeuCoin'
};
